[package]
name = "libhelix"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true

[lib]
name = "helix"
crate-type = ["staticlib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
cbindgen = "0.24"
